# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 19:24
from __future__ import unicode_literals

import Grafistica.apps.viewer.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_key', models.PositiveIntegerField(choices=[(1, 'Line chart'), (2, 'Bar chart'), (3, 'Pie chart'), (4, 'Doughnut chart'), (5, 'Polar Area chart')], verbose_name='Tipo')),
                ('position_x', models.CharField(blank=True, max_length=100, null=True, verbose_name='Posición X')),
                ('position_y', models.CharField(blank=True, max_length=100, null=True, verbose_name='Posición Y')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='Posición')),
            ],
        ),
        migrations.CreateModel(
            name='DataAnalytic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=Grafistica.apps.viewer.models.DataAnalytic.file_path)),
                ('name', models.CharField(blank=True, max_length=10000, null=True)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_name', models.CharField(max_length=500)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=Grafistica.apps.viewer.models.FileTemp.file_path)),
            ],
        ),
        migrations.CreateModel(
            name='GraphExcelData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_name', models.CharField(max_length=500)),
                ('graph_key', models.IntegerField(default=1)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Grafistica.apps.viewer.models.UserProfile.image_path, verbose_name='Foto de perfil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfil de usuarios',
            },
        ),
        migrations.AddField(
            model_name='chart',
            name='data_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.DataAnalytic'),
        ),
    ]
