# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='type_key',
            field=models.PositiveIntegerField(choices=[(1, 'Line chart'), (2, 'Bar chart'), (3, 'Column chart'), (4, 'Pie chart'), (5, 'Spline chart'), (6, 'Basic Area Chart'), (7, 'Area Spline chart'), (8, 'Waterfall chart'), (9, 'Polygon chart'), (10, 'Scatter Chart')], verbose_name='Tipo'),
        ),
    ]
